# Constants use all CAPS
ROWS = 30
COLS = 30
TILE_SIZE = 32
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * ROWS
SCREEN_HEIGHT = TILE_SIZE * COLS
FPS = 60
HEALTH = 35
MONEY = 10000
TOTAL_LEVELS = 15  # 15 levels

# Enemy constants
SPAWN_COOLDOWN = 400  # Change number for balance changes (higher for easier)

# Turret Constants
TURRET_LEVELS = 4
BUY_COST = 200
UPGRADE_COST = 100
KILL_REWARD = 5
LEVEL_COMPLETE_REWARD = 100
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
DAMAGE = 5
REFUND_TURRET_RATE = 0.75
